name: SonarQube Analysis
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build-and-analyze:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set encoding
        run: echo "JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV

      - name: Build and analyze
        run: |
          # Primero verifica si el proyecto existe en SonarCloud
          if ! curl -s -u "$SONAR_TOKEN": "https://sonarcloud.io/api/projects/search?projects=xpablote_ejercicio-java" | grep -q '"projects":\[\]'; then
            echo "Proyecto ya existe en SonarCloud, procediendo con análisis..."
            mvn -B clean verify sonar:sonar \
              -Dsonar.organization=xpablote \
              -Dsonar.projectKey=xpablote_ejercicio-java \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.branch.name=${{ github.ref_name }} \
              -Dsonar.java.coveragePlugin=jacoco \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
              -Dsonar.junit.reportPaths=target/surefire-reports
          else
            echo "Proyecto no existe, realizando primer análisis con rama main..."
            mvn -B clean verify sonar:sonar \
              -Dsonar.organization=xpablote \
              -Dsonar.projectKey=xpablote_ejercicio-java \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.branch.name=main \
              -Dsonar.java.coveragePlugin=jacoco \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
              -Dsonar.junit.reportPaths=target/surefire-reports
          fi