name: SonarQube Analysis
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para el análisis completo de SonarQube
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Build with Maven and generate coverage
      run: |
        mvn -B clean verify 
        mvn jacoco:report  # Genera el informe de cobertura
        
    - name: Run SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automático de GitHub
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Token que ya configuraste
      with:
        args: >
          -Dsonar.organization=xPablote
          -Dsonar.projectKey=xPablote_ejercicio-java
          -Dsonar.java.coveragePlugin=jacoco
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.junit.reportPaths=target/surefire-reports
          -Dsonar.sourceEncoding=UTF-8
