name: SonarQube Analysis
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para el análisis completo de SonarQube

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Actualizado a v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set encoding
        run: echo "JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV

      - name: Run SonarQube Analysis
        run: |
          mvn -B sonar:sonar \
            -Dsonar.organization=xPablote \
            -Dsonar.projectKey=xPablote_ejercicio-java \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para la integración
